### ISSUE TITLE
Setup Monitoring server

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/ServerDeployment#14]

**Comment by Thomsen96** [comment]
We have currently reached the limit of droplets we are allowed to create. 

![billede](https://user-images.githubusercontent.com/32035863/157624812-91cba912-a981-4e85-9d42-939246785b80.png)

I have created a ticket with Digital ocean last night. but now reply yet. Awaiting information from Digital ocean

**Comment by Thomsen96** [comment]
The reply from Digital ocean:

> 
> Hi Jonas, 
> 
> Thank you so much for reaching out to us for getting the Droplet limit increased, Unfortunately, your account does not qualify for the requested limit based on our internal assessment guidelines. 
> 
> We would be happy to consider your request for a higher Droplet limit after you have established additional billing history with us with no instances of abuse. 
> 
> We hope you would understand we have these guidelines in place to ensure the stability of our platform.
> 
> Please feel free to reach out to us if you have any additional queries. We’re always here for you!

I have asked back what it specifically means and how we become qualified. But maybe we should look into other alternatives.

**Comment by Lucki2g** [comment]
We could always host the monitoring server on another digital ocean account, if it comes to that

**Comment by Thomsen96** [comment]
They have responded:

> Hi there, 
> 
> Thanks for writing back to us. Upon further review, we have gone ahead and increased the droplet limit to 5 on your account. 
> 
> We apologize for the confusion here.
> 
> Feel free to reach us out anytime if you have any other questions. 
> 

So i have now been able to create a new droplet and are now waiting for the DNS to go through for

- grafana.thomsen-it.dk
- monitoring.thomsen-it.dk
- prometheus.thomsen-it.dk
